import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse10554 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getTargetPath();
}
}